DROP TABLE IF EXISTS Player;

CREATE TABLE Player (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) DEFAULT NULL,
  surname VARCHAR(250)DEFAULT NULL,
  sex VARCHAR(250) DEFAULT NULL,
  dateOfBirth DATE DEFAULT NULL);



